### PR TITLE
Making the readme a bit more clearer. 

### PR DESCRIPTION
**Pull request by CounsellorPolonius**
Just moved some stuff around, explained some things more clearly and tidied the readme up. Kept a lot of the original text. I just added some to it.

### CODE REVIEW

**Comment by solcloud** [comment]
Hi, thank you for PR!. I push few changes. So please take a look at it and write back what you think about it? Mainly I want promo image to be more on top and also not so sure about "can mix and match package managers" so I rewrite that section little but I am open for discussion so feel free to send suggestions.

**Review by CounsellorPolonius — COMMENTED** [review]
Alright, I can work with that. Only minor things I could change are: 

following user defined --> following a user defined
Presets abstract list of your required packages to install --> Not sure what 'presets abstract list' means. It's a little confusing. 

I guess promo can stay up higher. I think we should add a blurb of what we're looking at in the screenshot though. Just to be more specific.

**Comment by solcloud** [comment]
I push some changes so please look at it and give feedback.

I decided to delete promo - It is my not so riced desktop after all and NiceOS main theme is that it can build anything user wants so why promoting my preset, if anybody interest they can watch it on youtube or build themself. 

For that "preset abstractions" I remove it also and add more text to preset "docs". It is probably not necessary to be in main readme and we can always improve presets docs than spamming main readme I think.

**Comment by CounsellorPolonius** [comment]
whoops, sorry. not super familiar with how github is. I didn't mean to put those images in the PR. Just ignore them for now (just messing around with logos and designs). Alright. Let me see this revision.

**Comment by CounsellorPolonius** [comment]
Yeah, I agree with the changes. I think you could eventually have a screenshot section just to show things running on it. It would just need an explanation of what the user is looking at. It all seems good.

**Comment by solcloud** [comment]
Ok, then I think we can merge this.

**Comment by solcloud** [comment]
I need to force push it to merge it, you can still find your original tree here https://github.com/CounsellorPolonius/NiceOS-Testing/tree/6a3f8fc24ad87b199b84348bdec82c75c9a5f6d0 
Thanks for PR!

**Comment by CounsellorPolonius** [comment]
Awesome, glad it's been added. I added a possible logo design to my repo if you want to take a look. Feel free to use it. It's in the artwork folder.

**Comment by solcloud** [comment]
Thank you for putting logo together, but I don't think that NiceOS needs logo really. It is others system "generator" so I think that everybody that use it will probably rename it to their liking like hostname (which is preset name by default) or [/etc/issue](https://github.com/solcloud/NiceOS/blob/master/target/etc/issue) . I do not want to force by default any boot splash screen logo or having NiceOS string in every corner of OS. When (if ever) this project became popular enough we can create one for marketing purposes which I will reveal live in some talk show :smile:.

It is just nice tool to make your dream OS :smiling_face_with_tear:

**Comment by CounsellorPolonius** [comment]
Fair enough. Makes a lot of sense. If I have any more documentation to add, i'll be sure to contact you.

:)

**Pull request merged**
